<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.4" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="11.3.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.4" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.4" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.4" />
    <PackageReference Include="Avalonia.Xaml.Interactions" Version="11.3.0.6" />
    <PackageReference Include="AvaloniaHotMarkdown" Version="0.2.3" />
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.69.0.3783" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="Markdown.Avalonia.Tight" Version="11.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AvaloniaHotMarkdown">
      <HintPath>..\..\Avalonia.HotMarkdown\AvaloniaHotMarkdown\bin\Debug\net9.0\AvaloniaHotMarkdown.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Update="Assets\credentials.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\credentials.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
